/**
 * facturacion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Facturacion);
  }
}(this, function(expect, Facturacion) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Facturacion.Article();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Article', function() {
    it('should create an instance of Article', function() {
      // uncomment below and update the code to test Article
      //var instance = new Facturacion.Article();
      //expect(instance).to.be.a(Facturacion.Article);
    });

    it('should have the property articleId (base name: "articleId")', function() {
      // uncomment below and update the code to test the property articleId
      //var instance = new Facturacion.Article();
      //expect(instance).to.be();
    });

    it('should have the property inventoryId (base name: "inventoryId")', function() {
      // uncomment below and update the code to test the property inventoryId
      //var instance = new Facturacion.Article();
      //expect(instance).to.be();
    });

    it('should have the property stockQuantity (base name: "stockQuantity")', function() {
      // uncomment below and update the code to test the property stockQuantity
      //var instance = new Facturacion.Article();
      //expect(instance).to.be();
    });

    it('should have the property costPrice (base name: "costPrice")', function() {
      // uncomment below and update the code to test the property costPrice
      //var instance = new Facturacion.Article();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Facturacion.Article();
      //expect(instance).to.be();
    });

    it('should have the property inventory (base name: "inventory")', function() {
      // uncomment below and update the code to test the property inventory
      //var instance = new Facturacion.Article();
      //expect(instance).to.be();
    });

  });

}));
