/**
 * facturacion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Facturacion);
  }
}(this, function(expect, Facturacion) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Facturacion.Customer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Customer', function() {
    it('should create an instance of Customer', function() {
      // uncomment below and update the code to test Customer
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be.a(Facturacion.Customer);
    });

    it('should have the property customerId (base name: "customerId")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be();
    });

    it('should have the property rtn (base name: "rtn")', function() {
      // uncomment below and update the code to test the property rtn
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be();
    });

    it('should have the property customerType (base name: "customerType")', function() {
      // uncomment below and update the code to test the property customerType
      //var instance = new Facturacion.Customer();
      //expect(instance).to.be();
    });

  });

}));
