/**
 * facturacion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Article from './Article';

/**
 * The Inventory model module.
 * @module model/Inventory
 * @version 1.0
 */
class Inventory {
    /**
     * Constructs a new <code>Inventory</code>.
     * @alias module:model/Inventory
     */
    constructor() { 
        
        Inventory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Inventory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Inventory} obj Optional instance to populate.
     * @return {module:model/Inventory} The populated <code>Inventory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Inventory();

            if (data.hasOwnProperty('inventoryId')) {
                obj['inventoryId'] = ApiClient.convertToType(data['inventoryId'], 'String');
            }
            if (data.hasOwnProperty('article')) {
                obj['article'] = ApiClient.convertToType(data['article'], [Article]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Inventory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Inventory</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['inventoryId'] && !(typeof data['inventoryId'] === 'string' || data['inventoryId'] instanceof String)) {
            throw new Error("Expected the field `inventoryId` to be a primitive type in the JSON string but got " + data['inventoryId']);
        }
        if (data['article']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['article'])) {
                throw new Error("Expected the field `article` to be an array in the JSON data but got " + data['article']);
            }
            // validate the optional field `article` (array)
            for (const item of data['article']) {
                Article.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} inventoryId
 */
Inventory.prototype['inventoryId'] = undefined;

/**
 * @member {Array.<module:model/Article>} article
 */
Inventory.prototype['article'] = undefined;






export default Inventory;

